- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.37.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: no-commit-to-branch
      args: [--branch, master]
    - id: check-yaml
    - id: check-merge-conflict
